import { useEffect, useState } from "react";
import { Cookie, Settings2, X } from "lucide-react";
import { api } from "../api/client";

const STORAGE_KEY = "va_cookie_preferences";
type Preferences = { essential: true; analytics: boolean; marketing: boolean };

export default function CookieConsent() {
  const [open, setOpen] = useState(false);
  const [manage, setManage] = useState(false);
  const [analytics, setAnalytics] = useState(false);
  const [marketing, setMarketing] = useState(false);
  useEffect(() => { if (!localStorage.getItem(STORAGE_KEY)) setOpen(true); }, []);
  function save(next: Preferences) { localStorage.setItem(STORAGE_KEY, JSON.stringify(next)); setOpen(false); setManage(false); void api.post("/legal/cookies", next).catch(() => {}); }
  if (!open) return null;
  return <div className="fixed inset-x-0 bottom-0 z-[120] p-4"><div className="mx-auto max-w-4xl rounded-2xl border border-line bg-panel p-5 shadow-2xl backdrop-blur"><div className="flex gap-4"><div className="hidden h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-accent-soft text-accent sm:flex"><Cookie size={19}/></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">Cookie preferences</h2><p className="mt-1 text-sm leading-5 text-ink-muted">VisionAttend uses essential browser storage for sign-in and interface settings. Optional analytics and marketing storage are off unless you choose them.</p></div><button onClick={()=>save({essential:true,analytics:false,marketing:false})} className="text-ink-faint hover:text-ink" aria-label="Use essential storage only"><X size={18}/></button></div>{manage&&<div className="mt-4 space-y-3 rounded-xl border border-line bg-bg p-4"><label className="flex items-start gap-3"><input type="checkbox" checked disabled className="mt-1"/><span><span className="block text-sm font-medium">Essential</span><span className="text-xs text-ink-muted">Required for authentication and core functionality.</span></span></label><label className="flex items-start gap-3"><input type="checkbox" checked={analytics} onChange={e=>setAnalytics(e.target.checked)} className="mt-1"/><span><span className="block text-sm font-medium">Analytics</span><span className="text-xs text-ink-muted">Optional measurement if enabled by the deployment.</span></span></label><label className="flex items-start gap-3"><input type="checkbox" checked={marketing} onChange={e=>setMarketing(e.target.checked)} className="mt-1"/><span><span className="block text-sm font-medium">Marketing</span><span className="text-xs text-ink-muted">Optional marketing or personalization storage if introduced later.</span></span></label></div>}<div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>save({essential:true,analytics:false,marketing:false})} className="rounded-xl border border-line px-4 py-2 text-sm">Essential only</button>{manage?<button onClick={()=>save({essential:true,analytics,marketing})} className="rounded-xl bg-accent px-4 py-2 text-sm font-medium text-white">Save preferences</button>:<button onClick={()=>setManage(true)} className="inline-flex items-center gap-2 rounded-xl border border-line px-4 py-2 text-sm"><Settings2 size={15}/> Manage</button>}<button onClick={()=>save({essential:true,analytics:true,marketing:true})} className="rounded-xl bg-accent px-4 py-2 text-sm font-medium text-white">Accept all</button></div><p className="mt-3 text-xs text-ink-faint">Read our <a className="text-accent hover:underline" href="/cookies">Cookie Policy</a> and manage preferences later from the site footer.</p></div></div></div></div>;
}
