import { useEffect, useMemo, useState } from "react";
import { Radio, Square, Users, CheckCircle2, Clock3, Activity, Menu, CalendarClock, Play } from "lucide-react";
import { api } from "../api/client";
import AdminSidebar from "../components/AdminSidebar";

type Session={session_id:string;name:string;start_time?:string;duration_minutes?:number;status?:string};
type AttendanceRecord={student_id?:string;name?:string;status?:string;time?:string;timestamp?:string};

export default function AdminLiveSessionPage(){
 const [sidebarOpen,setSidebarOpen]=useState(false); const [session,setSession]=useState<Session|null>(null); const [scheduled,setScheduled]=useState<Session[]>([]); const [records,setRecords]=useState<AttendanceRecord[]>([]); const [pipelineRunning,setPipelineRunning]=useState(false); const [loading,setLoading]=useState(false); const [seconds,setSeconds]=useState(0); const [error,setError]=useState("");
 async function load(){try{const [currentRes,scheduledRes,pipelineRes]=await Promise.all([api.get("/session/current"),api.get("/session/scheduled"),api.get("/pipeline/status")]);const c=currentRes.data;const current=c?.active?c:null;setSession(current);setScheduled(scheduledRes.data?.sessions??[]);setPipelineRunning(Boolean(pipelineRes.data?.running));if(current?.session_id){const a=await api.get(`/attendance/session/${current.session_id}`);setRecords(a.data.records??[])}else setRecords([])}catch(e){console.error(e)}}
 useEffect(()=>{void load();const t=window.setInterval(()=>void load(),3000);return()=>window.clearInterval(t)},[]);
 useEffect(()=>{if(!session?.start_time){setSeconds(0);return}const t=window.setInterval(()=>{const remaining=Math.max(0,(session.duration_minutes??45)*60-Math.floor((Date.now()-new Date(session.start_time!).getTime())/1000));setSeconds(remaining)},1000);return()=>window.clearInterval(t)},[session]);
 const timer=useMemo(()=>`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`,[seconds]);
 const present=records.filter(r=>r.status?.toLowerCase()==="present").length; const late=records.filter(r=>r.status?.toLowerCase()==="late").length;
 async function startNow(){setLoading(true);setError("");try{await api.post("/session/start",{name:"Attendance Session",duration_minutes:45,late_after_minutes:10});await load()}catch(e:any){setError(e?.response?.data?.detail??"Could not start session.")}finally{setLoading(false)}}
 async function startScheduled(id:string){setLoading(true);setError("");try{await api.post(`/session/start/${id}`);await load()}catch(e:any){setError(e?.response?.data?.detail??"Could not start scheduled session.")}finally{setLoading(false)}}
 async function stop(){setLoading(true);setError("");try{await api.post("/session/end");await load()}catch(e:any){setError(e?.response?.data?.detail??"Could not stop session.")}finally{setLoading(false)}}
 const active=Boolean(session?.session_id); const next=scheduled[0];
 return <div className="min-h-screen bg-bg text-ink"><AdminSidebar open={sidebarOpen} onClose={()=>setSidebarOpen(false)}/><div className="lg:pl-64"><header className="sticky top-0 z-30 border-b border-line bg-bg/90 backdrop-blur-md"><div className="flex h-16 items-center gap-4 px-5 sm:px-8"><button onClick={()=>setSidebarOpen(true)} className="rounded-lg border border-line bg-panel p-2 lg:hidden"><Menu size={19}/></button><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-accent">Admin Portal</p><h1 className="font-display text-xl font-semibold">Live Session</h1></div></div></header>
 <main className="mx-auto max-w-7xl px-5 py-7 sm:px-8"><div className="mb-7"><p className="text-sm text-ink-muted">Control and monitor the active AI attendance session.</p></div>
 <section className="rounded-2xl border border-line bg-panel p-6 shadow-sm"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-center"><div className="flex items-center gap-4"><div className={`flex h-14 w-14 items-center justify-center rounded-2xl ${active?"bg-red-50 text-red-600":"bg-accent-soft text-accent"}`}><Radio size={26}/></div><div><p className="text-xs uppercase tracking-wider text-ink-faint">Session status</p><h2 className="mt-1 text-xl font-semibold">{active?"AI Session Active":"No Active Session"}</h2><div className="mt-2 flex items-center gap-2 text-sm text-ink-muted"><Activity size={15}/>{pipelineRunning?"ML pipeline running":"ML pipeline stopped"}</div></div></div>{!active?<button onClick={startNow} disabled={loading} className="flex items-center justify-center gap-2 rounded-xl bg-accent px-6 py-3 font-medium text-white disabled:opacity-50"><Radio size={18}/>{loading?"Starting...":"Start 45-Minute Session"}</button>:<button onClick={stop} disabled={loading} className="flex items-center justify-center gap-2 rounded-xl bg-red-600 px-6 py-3 font-medium text-white disabled:opacity-50"><Square size={17}/>{loading?"Stopping...":"Stop Session"}</button>}</div>{error&&<p className="mt-4 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-600">{error}</p>}</section>
 {next&&!active&&<section className="mt-5 rounded-2xl border border-line bg-panel p-5 shadow-sm"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div className="flex items-center gap-3"><div className="rounded-xl bg-accent-soft p-3 text-accent"><CalendarClock size={20}/></div><div><p className="text-xs uppercase tracking-wider text-ink-faint">Scheduled next</p><h3 className="font-semibold">{next.name}</h3><p className="text-sm text-ink-muted">{next.start_time?new Date(next.start_time).toLocaleString():"—"} · 45 min</p></div></div><button onClick={()=>startScheduled(next.session_id)} disabled={loading} className="flex items-center gap-2 rounded-xl bg-accent px-5 py-3 text-sm font-medium text-white disabled:opacity-50"><Play size={16}/>{loading?"Starting...":"Start Scheduled Session"}</button></div></section>}
 <section className="mt-5 grid gap-4 md:grid-cols-3"><InfoCard icon={<Clock3 size={20}/>} title="Time Remaining" value={active?timer:"45:00"}/><InfoCard icon={<Users size={20}/>} title="Present" value={present.toString()}/><InfoCard icon={<CheckCircle2 size={20}/>} title="Late" value={late.toString()}/></section>
 <section className="mt-6 rounded-2xl border border-line bg-panel shadow-sm"><div className="flex items-center justify-between border-b border-line px-5 py-4"><div><h2 className="font-semibold">Live Attendance</h2><p className="mt-1 text-xs text-ink-muted">Attendance detected by the AI pipeline for this session</p></div><div className={`flex items-center gap-2 text-xs ${active?"text-present":"text-ink-muted"}`}><span className={`h-2 w-2 rounded-full ${active?"bg-present":"bg-ink-faint"}`}/>{active?"Live":"Closed"}</div></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-line bg-panel-hover text-xs uppercase tracking-wider text-ink-faint"><tr><th className="px-5 py-3">Student</th><th className="px-5 py-3">ID</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Time</th></tr></thead><tbody>{records.map((r,i)=><tr key={`${r.student_id}-${i}`} className="border-b border-line last:border-0"><td className="px-5 py-4 font-medium">{r.name??"Unknown"}</td><td className="px-5 py-4 text-ink-muted">{r.student_id??"—"}</td><td className="px-5 py-4"><span className="rounded-full bg-accent-soft px-3 py-1 text-xs font-medium text-accent">{r.status??"Recorded"}</span></td><td className="px-5 py-4 text-ink-muted">{r.time??r.timestamp??"—"}</td></tr>)}{!records.length&&<tr><td colSpan={4} className="px-5 py-12 text-center text-sm text-ink-muted">{active?"No attendance detected yet.":"No active session attendance."}</td></tr>}</tbody></table></div></section>
 </main></div></div>
}
function InfoCard({icon,title,value}:{icon:React.ReactNode;title:string;value:string}){return <div className="rounded-2xl border border-line bg-panel p-5 shadow-sm"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-accent-soft text-accent">{icon}</div><div><p className="text-xs uppercase tracking-wider text-ink-faint">{title}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div></div></div>}
