import { useEffect, useMemo, useState } from "react";
import { ChevronDown, ChevronLeft, ChevronRight, Users } from "lucide-react";
import AdminSidebar from "../components/AdminSidebar";
import { api } from "../api/client";

type Student={student_id:string;name:string}; type RecordItem={student_id:string;name:string;status:string;date?:string;time?:string;session_id?:string};
const PAGE_SIZE=6; const RECORD_PAGE_SIZE=6;
export default function AdminAttendancePage(){
 const [students,setStudents]=useState<Student[]>([]); const [records,setRecords]=useState<RecordItem[]>([]); const [open,setOpen]=useState<string|null>(null); const [page,setPage]=useState(1); const [recordPage,setRecordPage]=useState(1); const [loading,setLoading]=useState(true);
 useEffect(()=>{async function load(){try{const sr=await api.get("/students");const people=sr.data.students??[];setStudents(people);const results=await Promise.all(people.map((s:Student)=>api.get(`/students/${s.student_id}/attendance`).then(r=>r.data.records??[]).catch(()=>[])));setRecords(results.flat() as RecordItem[]);}finally{setLoading(false)}}void load()},[]);
 const grouped=useMemo(()=>{const m=new Map<string,RecordItem[]>();for(const r of records){const id=r.session_id??`date-${r.date}`;(m.get(id)??m.set(id,[]).get(id)!).push(r)}return m},[records]);
 const entries=Array.from(grouped.entries()); const totalPages=Math.max(1,Math.ceil(entries.length/PAGE_SIZE)); const visible=entries.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);
 const opened=entries.find(([id])=>id===open)?.[1]??[]; const recordPages=Math.max(1,Math.ceil(opened.length/RECORD_PAGE_SIZE)); const visibleRecords=opened.slice((recordPage-1)*RECORD_PAGE_SIZE,recordPage*RECORD_PAGE_SIZE);
 function toggle(id:string){setOpen(open===id?null:id);setRecordPage(1);}
 return <div className="min-h-screen bg-bg text-ink"><AdminSidebar/><div className="lg:pl-64"><main className="mx-auto max-w-7xl px-5 py-8 sm:px-8"><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-accent">Admin Portal</p><h1 className="mt-1 font-display text-3xl font-semibold">Attendance History</h1><p className="mt-2 text-sm text-ink-muted">Session-wise history without an endless audit list.</p>
 <section className="mt-6 grid gap-4 sm:grid-cols-3"><Stat label="Students" value={students.length}/><Stat label="Sessions Tracked" value={grouped.size}/><Stat label="Attendance Records" value={records.length}/></section>
 <section className="mt-6 rounded-2xl border border-line bg-panel shadow-sm"><div className="border-b border-line px-6 py-5"><h2 className="font-semibold">Session History</h2><p className="mt-1 text-xs text-ink-muted">Showing {visible.length} of {entries.length} sessions.</p></div>{loading?<p className="p-8 text-sm text-ink-muted">Loading attendance history...</p>:visible.map(([id,rs])=>{const p=rs.filter(r=>r.status.toLowerCase()==="present").length,l=rs.filter(r=>r.status.toLowerCase()==="late").length,a=rs.filter(r=>r.status.toLowerCase()==="absent").length;return <div key={id} className="border-b border-line last:border-0"><button onClick={()=>toggle(id)} className="flex w-full items-center justify-between px-6 py-5 text-left hover:bg-panel-hover"><div><p className="font-semibold">Session {id.startsWith("date-")?id.slice(5):id.slice(-8)}</p><p className="mt-1 text-xs text-ink-muted">{rs[0]?.date??"—"} · {rs.length} records</p></div><div className="flex items-center gap-4"><span className="hidden text-xs sm:block"><b className="text-green-700">{p} Present</b> · <b>{l} Late</b> · <b className="text-red-600">{a} Absent</b></span><ChevronDown size={18} className={open===id?"rotate-180":""}/></div></button>{open===id&&<div className="bg-bg/40 p-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{visibleRecords.map((r,i)=><div key={`${r.student_id}-${i}`} className="rounded-xl border border-line bg-panel p-4"><div className="flex items-center gap-3"><div className="rounded-lg bg-accent-soft p-2 text-accent"><Users size={16}/></div><div><p className="font-medium">{r.name}</p><p className="text-xs text-ink-muted">{r.student_id}</p></div></div><div className="mt-3 flex justify-between text-xs"><span className="rounded-full bg-accent-soft px-2 py-1 text-accent">{r.status}</span><span className="text-ink-muted">{r.time??"—"}</span></div></div>)}</div>{recordPages>1&&<Pager page={recordPage} total={recordPages} onChange={setRecordPage}/>}</div>}</div>})}{!loading&&!entries.length&&<p className="p-10 text-center text-sm text-ink-muted">No session attendance records yet.</p>} {!loading&&entries.length>0&&<Pager page={page} total={totalPages} onChange={setPage}/>}</section>
 </main></div></div>;
}
function Pager({page,total,onChange}:{page:number;total:number;onChange:(p:number)=>void}){return <div className="flex items-center justify-center gap-3 border-t border-line px-5 py-4"><button disabled={page===1} onClick={()=>onChange(page-1)} className="rounded-lg border border-line p-2 disabled:opacity-30 hover:bg-panel-hover"><ChevronLeft size={16}/></button><span className="text-xs text-ink-muted">Page {page} of {total}</span><button disabled={page===total} onClick={()=>onChange(page+1)} className="rounded-lg border border-line p-2 disabled:opacity-30 hover:bg-panel-hover"><ChevronRight size={16}/></button></div>}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-line bg-panel p-5 shadow-sm"><p className="text-xs uppercase tracking-wider text-ink-faint">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></div>}
