import { useEffect, useMemo, useState } from "react";
import { CalendarClock, ChevronDown, ChevronLeft, ChevronRight, Users, CircleCheck, CircleX, Clock3 } from "lucide-react";
import AdminSidebar from "../components/AdminSidebar";
import { api } from "../api/client";

type Student={student_id:string;name:string};
type RecordItem={student_id:string;name:string;status:string;date?:string;time?:string;session_id?:string};
type Session={session_id:string;name:string;start_time:string;planned_start_time?:string;duration_minutes:number;status:string};
const PAGE_SIZE=6, RECORD_PAGE_SIZE=6;
const tone=(s?:string)=>s?.toLowerCase()==="present"?"bg-mint-soft text-present":s?.toLowerCase()==="late"?"bg-sky-soft text-sky":"bg-rose-soft text-absent";

export default function AdminAttendancePage(){
 const[students,setStudents]=useState<Student[]>([]),[records,setRecords]=useState<RecordItem[]>([]),[sessions,setSessions]=useState<Session[]>([]),[open,setOpen]=useState<string|null>(null),[page,setPage]=useState(1),[recordPage,setRecordPage]=useState(1),[loading,setLoading]=useState(true);
 useEffect(()=>{async function load(){try{const[sr,hr]=await Promise.all([api.get("/students"),api.get("/session/history")]);const people=sr.data.students??[];setStudents(people);setSessions(hr.data.sessions??[]);const rs=await Promise.all(people.map((s:Student)=>api.get(`/students/${s.student_id}/attendance`).then(r=>r.data.records??[]).catch(()=>[])));setRecords(rs.flat() as RecordItem[])}catch(e){console.error(e)}finally{setLoading(false)}}void load()},[]);
 const sessionMap=useMemo(()=>new Map(sessions.map(s=>[s.session_id,s])),[sessions]);
 const grouped=useMemo(()=>{const m=new Map<string,RecordItem[]>();records.forEach(r=>{const id=r.session_id??`date-${r.date}`;const bucket=m.get(id);if(bucket)bucket.push(r);else m.set(id,[r])});return m},[records]);
 const entries=Array.from(grouped.entries());
 const totalPages=Math.max(1,Math.ceil(entries.length/PAGE_SIZE));
 const visible=entries.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);
 const totals=useMemo(()=>{const latest=new Map<string,RecordItem>();records.forEach(r=>{const key=`${r.student_id}-${r.session_id??r.date}`;latest.set(key,r)});return Array.from(latest.values()).reduce((a,r)=>{const s=r.status.toLowerCase();if(s==="present")a.present++;else if(s==="late")a.late++;else if(s==="absent")a.absent++;return a},{present:0,late:0,absent:0})},[records]);
 function toggle(id:string){setOpen(open===id?null:id);setRecordPage(1)}
 function changePage(next:number){setPage(Math.min(totalPages,Math.max(1,next)));setOpen(null)}
 return <div className="min-h-screen bg-bg text-ink"><AdminSidebar/><main className="w-full px-5 py-8 sm:px-8 lg:px-10 transition-[margin-left,width] duration-300" style={{marginLeft:"var(--portal-sidebar-offset,0px)",width:"calc(100% - var(--portal-sidebar-offset,0px))"}}><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-accent">Admin Portal</p><h1 className="mt-1 font-display text-3xl font-semibold">Attendance History</h1><p className="mt-2 text-sm text-ink-muted">Session-wise history with the actual session name and time.</p>
 <div className="mt-6 grid gap-4 sm:grid-cols-3"><Stat icon={<CircleCheck size={19}/>} label="Present" value={totals.present} cls="bg-mint-soft text-present"/><Stat icon={<Clock3 size={19}/>} label="Late" value={totals.late} cls="bg-sky-soft text-sky"/><Stat icon={<CircleX size={19}/>} label="Absent" value={totals.absent} cls="bg-rose-soft text-absent"/></div>
 <section className="mt-6 overflow-hidden rounded-2xl border border-line bg-panel shadow-sm"><div className="border-b border-line px-6 py-5"><h2 className="font-semibold">Session History</h2><p className="mt-1 text-xs text-ink-muted">Showing {visible.length} of {entries.length} sessions.</p></div>{loading?<p className="p-8 text-sm text-ink-muted">Loading attendance history...</p>:visible.map(([id,rs])=>{const p=rs.filter(r=>r.status.toLowerCase()==="present").length,l=rs.filter(r=>r.status.toLowerCase()==="late").length,a=rs.filter(r=>r.status.toLowerCase()==="absent").length,s=sessionMap.get(id);return <div key={id} className="border-b border-line last:border-0"><button onClick={()=>toggle(id)} className="flex w-full items-center justify-between gap-4 px-6 py-5 text-left hover:bg-panel-hover"><div className="flex min-w-0 items-center gap-3"><div className="rounded-lg bg-lavender-soft p-2 text-lavender"><CalendarClock size={17}/></div><div className="min-w-0"><p className="truncate font-semibold">{s?.name??"Session"}</p><p className="mt-1 text-xs text-ink-muted">{s?new Date(s.planned_start_time||s.start_time).toLocaleDateString(undefined,{weekday:"short",month:"short",day:"numeric",year:"numeric"}):rs[0]?.date??"Date unavailable"} · {s?new Date(s.start_time).toLocaleTimeString(undefined,{hour:"numeric",minute:"2-digit"}):"Time unavailable"} · {rs.length} records</p></div></div><div className="flex shrink-0 items-center gap-4"><span className="hidden text-xs sm:flex sm:gap-2"><b className="rounded-full bg-mint-soft px-2 py-1 text-present">{p} Present</b><b className="rounded-full bg-sky-soft px-2 py-1 text-sky">{l} Late</b><b className="rounded-full bg-rose-soft px-2 py-1 text-absent">{a} Absent</b></span><ChevronDown size={18} className={open===id?"rotate-180":""}/></div></button>{open===id&&<Details records={rs} page={recordPage} setPage={setRecordPage}/>}</div>})}{!loading&&!entries.length&&<p className="p-10 text-center text-sm text-ink-muted">No session attendance records yet.</p>}{!loading&&entries.length>0&&<Pager page={page} total={totalPages} onChange={changePage}/>}</section></main></div>
}
function Details({records,page,setPage}:{records:RecordItem[];page:number;setPage:(p:number)=>void}){const pages=Math.max(1,Math.ceil(records.length/RECORD_PAGE_SIZE)),visible=records.slice((page-1)*RECORD_PAGE_SIZE,page*RECORD_PAGE_SIZE);return <div className="bg-bg/40 p-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{visible.map((r,i)=><div key={`${r.student_id}-${i}`} className="rounded-xl border border-line bg-panel p-4"><div className="flex items-center gap-3"><div className={`rounded-lg p-2 ${tone(r.status)}`}><Users size={16}/></div><div><p className="font-medium">{r.name}</p><p className="text-xs text-ink-muted">{r.student_id}</p></div></div><div className="mt-3 flex items-center justify-between"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${tone(r.status)}`}>{r.status}</span><span className="text-xs text-ink-muted">{r.time??"—"}</span></div></div>)}</div>{pages>1&&<Pager page={page} total={pages} onChange={setPage}/>}</div>}
function Pager({page,total,onChange}:{page:number;total:number;onChange:(p:number)=>void}){return <div className="flex items-center justify-center gap-3 border-t border-line px-5 py-4"><button disabled={page===1} onClick={()=>onChange(page-1)} className="rounded-lg border border-line p-2 disabled:opacity-30 hover:bg-panel-hover"><ChevronLeft size={16}/></button><span className="text-xs text-ink-muted">Page {page} of {total}</span><button disabled={page===total} onClick={()=>onChange(page+1)} className="rounded-lg border border-line p-2 disabled:opacity-30 hover:bg-panel-hover"><ChevronRight size={16}/></button></div>}
function Stat({icon,label,value,cls}:{icon:React.ReactNode;label:string;value:number;cls:string}){return <div className="rounded-2xl border border-line bg-panel p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className={`flex h-11 w-11 items-center justify-center rounded-xl ${cls}`}>{icon}</div><p className="mt-4 text-xs uppercase tracking-wider text-ink-faint">{label}</p><p className="mt-1 text-3xl font-semibold">{value}</p></div>}
