import { useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, CalendarClock, CheckCircle2, Clock3, Trash2, Users, XCircle } from "lucide-react";
import { Link } from "react-router-dom";
import { api } from "../api/client";
import { useAuth } from "../context/AuthContext";
import AdminSidebar from "../components/AdminSidebar";

type Student={student_id:string;name:string};
type Attendance={student_id?:string;name?:string;status?:string;time?:string;date?:string;session_id?:string};
type Session={session_id:string;name:string;start_time:string;planned_start_time?:string;duration_minutes:number;status:string};

function sortTime(a:Attendance,b:Attendance){return `${b.date||""} ${b.time||""}`.localeCompare(`${a.date||""} ${a.time||""}`)}
function latestPerStudent(records:Attendance[]){const map=new Map<string,Attendance>();[...records].sort(sortTime).forEach(r=>{const id=r.student_id||r.name||"unknown";if(!map.has(id))map.set(id,r)});return [...map.values()]}
function countStatuses(records:Attendance[]){return latestPerStudent(records).reduce((a,r)=>{const s=r.status?.toLowerCase();if(s==="present")a.present++;else if(s==="late")a.late++;else if(s==="absent")a.absent++;return a},{present:0,late:0,absent:0})}

export default function AdminDashboardPage(){
 const {name}=useAuth();const[students,setStudents]=useState<Student[]>([]),[records,setRecords]=useState<Attendance[]>([]),[scheduled,setScheduled]=useState<Session[]>([]),[session,setSession]=useState<Session|null>(null),[latestSession,setLatestSession]=useState<Session|null>(null),[pipelineRunning,setPipelineRunning]=useState(false),[loading,setLoading]=useState(true),[showClearHistory,setShowClearHistory]=useState(false),[clearingHistory,setClearingHistory]=useState(false),[clearError,setClearError]=useState("");
 async function load(){try{const[studentsRes,currentRes,scheduledRes,statusRes,historyRes]=await Promise.all([api.get("/students"),api.get("/session/current"),api.get("/session/scheduled"),api.get("/pipeline/status"),api.get("/session/history")]);const current=currentRes.data?.active?currentRes.data:null;const people=studentsRes.data?.students??[];const history=(historyRes.data?.sessions??[]) as Session[];const ordered=[...history,...(scheduledRes.data?.sessions??[])].sort((a:Session,b:Session)=>new Date(b.planned_start_time||b.start_time).getTime()-new Date(a.planned_start_time||a.start_time).getTime());setStudents(people);setSession(current);setScheduled(scheduledRes.data?.sessions??[]);setLatestSession(current||ordered[0]||null);setPipelineRunning(Boolean(statusRes.data?.running));const attendance=await Promise.all(people.map((s:Student)=>api.get(`/students/${s.student_id}/attendance`).then(r=>r.data.records??[]).catch(()=>[])));setRecords(attendance.flat() as Attendance[])}catch(e){console.error("Dashboard refresh failed",e)}finally{setLoading(false)}}
 useEffect(()=>{void load();const t=window.setInterval(()=>void load(),10000);return()=>window.clearInterval(t)},[]);
 async function clearHistory(){setClearingHistory(true);setClearError("");try{await api.delete("/admin/attendance-history");setShowClearHistory(false);await load()}catch(error:any){setClearError(error?.response?.data?.detail||"Could not clear attendance history.")}finally{setClearingHistory(false)}}
 const latestRecords=useMemo(()=>latestSession?records.filter(r=>r.session_id===latestSession.session_id):[],[records,latestSession]);
 const totals=useMemo(()=>countStatuses(latestRecords),[latestRecords]);
 const overallRate=students.length?Math.round(((totals.present+totals.late)/students.length)*100):0;const chartTotal=Math.max(students.length,1);const pieStyle={background:`conic-gradient(#15966a 0 ${(totals.present/chartTotal)*100}%, #258fd0 ${(totals.present/chartTotal)*100}% ${((totals.present+totals.late)/chartTotal)*100}%, #df4d55 ${((totals.present+totals.late)/chartTotal)*100}% 100%)`};
 const recent=useMemo(()=>{const m=new Map<string,{date:string;present:number;late:number;absent:number}>();records.forEach(r=>{const d=r.date||"Recent";const x=m.get(d)??{date:new Date(`${d}T00:00:00`).toLocaleDateString(undefined,{month:"short",day:"numeric"}),present:0,late:0,absent:0};const s=r.status?.toLowerCase();if(s==="present")x.present++;else if(s==="late")x.late++;else if(s==="absent")x.absent++;m.set(d,x)});return Array.from(m.values()).slice(-7)},[records]);
 const maxRecent=Math.max(...recent.map(x=>x.present+x.late+x.absent),1);const nextSession=scheduled[0];const sessionCount=new Set(records.map(r=>r.session_id).filter(Boolean)).size;
 return <div className="min-h-screen bg-bg text-ink"><AdminSidebar/><main className="w-full px-5 py-8 sm:px-8 lg:px-10 transition-[margin-left,width] duration-300" style={{marginLeft:"var(--portal-sidebar-offset,0px)",width:"calc(100% - var(--portal-sidebar-offset,0px))"}}><section className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-accent">Welcome back{name?`, ${name}`:""}</p><h2 className="mt-1 font-display text-3xl font-semibold sm:text-4xl">Attendance Overview</h2><p className="mt-2 text-sm text-ink-muted">Latest completed or active session for the cards below.</p></div><div className="flex items-center gap-2 rounded-xl border border-line bg-panel px-4 py-2.5 text-xs text-ink-muted shadow-sm"><span className={`h-2.5 w-2.5 rounded-full ${pipelineRunning?"animate-pulse bg-present":"bg-ink-faint"}`}/>{pipelineRunning?"AI Pipeline Active":"AI Pipeline Idle"}</div></section>
 <section className="rounded-2xl border border-line bg-panel px-5 py-3 text-xs text-ink-muted shadow-sm">{loading?"Loading latest session…":latestSession?<>Cards and pie chart are from <b className="text-ink">{latestSession.name}</b> · {new Date(latestSession.planned_start_time||latestSession.start_time).toLocaleString()}</>:"No attendance session recorded yet."}</section>
 <section className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={<Users size={20}/>} label="Total Students" value={students.length} tone="blue"/><Stat icon={<CheckCircle2 size={20}/>} label="Present · Latest Session" value={totals.present} tone="green"/><Stat icon={<Clock3 size={20}/>} label="Late · Latest Session" value={totals.late} tone="sky"/><Stat icon={<XCircle size={20}/>} label="Absent · Latest Session" value={totals.absent} tone="red"/></section>
 <section className="mt-6 grid gap-5 lg:grid-cols-[.82fr_1.18fr]"><div className="rounded-2xl border border-line bg-panel p-6 shadow-sm"><div className="flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-accent">Latest Session</p><h3 className="mt-1 text-lg font-semibold">Student Distribution</h3><p className="mt-1 text-xs text-ink-muted">One latest status per student in this session</p></div><span className="rounded-full bg-lavender-soft px-3 py-1 text-xs text-lavender">{latestSession?latestSession.name:"No session"}</span></div><div className="mt-7 flex flex-col items-center gap-6 sm:flex-row sm:justify-center"><div className="relative h-48 w-48 shrink-0 rounded-full" style={pieStyle}><div className="absolute inset-8 flex flex-col items-center justify-center rounded-full bg-panel"><span className="text-3xl font-semibold">{overallRate}%</span><span className="text-[11px] text-ink-muted">attendance</span></div></div><div className="w-full max-w-xs space-y-3"><Legend color="bg-present" label="Present" value={totals.present} total={chartTotal}/><Legend color="bg-late" label="Late" value={totals.late} total={chartTotal}/><Legend color="bg-absent" label="Absent" value={totals.absent} total={chartTotal}/></div></div></div><div className="rounded-2xl border border-line bg-panel p-6 shadow-sm"><div className="flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-accent">All Sessions</p><h3 className="mt-1 text-lg font-semibold">Historical Attendance</h3><p className="mt-1 text-xs text-ink-muted">Aggregate attendance events across recorded dates</p></div><Activity className="text-sky" size={20}/></div><div className="mt-6 space-y-4">{recent.length?recent.map((r,i)=><div key={`${r.date}-${i}`}><div className="mb-1.5 flex justify-between text-xs"><span className="font-medium">{r.date}</span><span className="text-ink-muted">{r.present+r.late+r.absent} records</span></div><div className="flex h-3 overflow-hidden rounded-full bg-line"><div className="bg-present" style={{width:`${r.present/maxRecent*100}%`}}/><div className="bg-late" style={{width:`${r.late/maxRecent*100}%`}}/><div className="bg-absent" style={{width:`${r.absent/maxRecent*100}%`}}/></div></div>):<p className="py-10 text-center text-sm text-ink-muted">No historical attendance yet.</p>}</div><div className="mt-5 flex flex-wrap gap-4 text-[11px] text-ink-muted"><span><i className="mr-1.5 inline-block h-2 w-2 rounded-full bg-present"/>Present</span><span><i className="mr-1.5 inline-block h-2 w-2 rounded-full bg-late"/>Late</span><span><i className="mr-1.5 inline-block h-2 w-2 rounded-full bg-absent"/>Absent</span></div></div></section>
 <section className="mt-6 grid gap-5 lg:grid-cols-[1fr_.65fr]"><div className="rounded-2xl border border-line bg-panel p-6 shadow-sm"><div className="flex items-center gap-3"><div className="rounded-xl bg-peach-soft p-3 text-accent"><CalendarClock size={20}/></div><div><p className="text-xs uppercase tracking-wider text-ink-faint">Next scheduled session</p><h3 className="mt-1 font-semibold">{nextSession?.name??"Nothing scheduled"}</h3></div></div>{nextSession?<><p className="mt-5 text-sm text-ink-muted">{new Date(nextSession.planned_start_time||nextSession.start_time).toLocaleString()}</p><p className="mt-1 text-xs text-ink-faint">45-minute AI monitoring session</p></>:<p className="mt-5 text-sm text-ink-muted">Schedule a lecture to see it here.</p>}<Link to="/admin/schedule" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-accent px-4 py-2.5 text-sm font-medium text-white"><CalendarClock size={16}/>Manage Schedule</Link></div><div className="rounded-2xl border border-line bg-panel p-6 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-accent">Database Summary</p><h3 className="mt-1 text-lg font-semibold">All Recorded Data</h3><p className="mt-1 text-xs text-ink-muted">Aggregate across all stored sessions, not the latest-session cards.</p></div><button onClick={()=>{setClearError("");setShowClearHistory(true)}} className="inline-flex shrink-0 items-center gap-2 rounded-xl border border-absent/25 bg-rose-soft px-3 py-2 text-xs font-semibold text-absent transition hover:-translate-y-0.5 hover:shadow-sm"><Trash2 size={14}/>Clear History</button></div><div className="mt-5 grid grid-cols-2 gap-3"><Mini label="Sessions" value={sessionCount} tone="lavender"/><Mini label="Records" value={records.length} tone="mint"/><Mini label="Present Records" value={records.filter(r=>r.status?.toLowerCase()==="present").length} tone="green"/><Mini label="Absent Records" value={records.filter(r=>r.status?.toLowerCase()==="absent").length} tone="red"/></div></div></section>
 {showClearHistory&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/45 px-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-2xl border border-line bg-panel p-6 shadow-2xl"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-rose-soft text-absent"><AlertTriangle size={24}/></div><h3 className="mt-4 text-xl font-semibold">Clear Attendance History?</h3><p className="mt-2 text-sm leading-6 text-ink-muted">This permanently removes all attendance records and completed session history. Your students, accounts and face embeddings will <b className="text-ink">not</b> be deleted.</p>{clearError&&<div className="mt-4 rounded-xl border border-absent/20 bg-rose-soft px-3 py-2 text-xs text-absent">{clearError}</div>}<div className="mt-6 flex justify-end gap-3"><button disabled={clearingHistory} onClick={()=>setShowClearHistory(false)} className="rounded-xl border border-line px-4 py-2.5 text-sm font-medium hover:bg-panel-hover">Cancel</button><button disabled={clearingHistory} onClick={()=>void clearHistory()} className="inline-flex items-center gap-2 rounded-xl bg-absent px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60"><Trash2 size={16}/>{clearingHistory?"Clearing…":"Clear History"}</button></div></div></div>}
 </main></div>;
}
function Stat({icon,label,value,tone}:{icon:React.ReactNode;label:string;value:string|number;tone:"blue"|"green"|"sky"|"red"}){const styles={blue:"bg-blue-soft border-blue/20 text-blue",green:"bg-mint-soft border-present/20 text-present",sky:"bg-sky-soft border-sky/20 text-sky",red:"bg-rose-soft border-absent/20 text-absent"};return <div className={`rounded-2xl border p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md ${styles[tone]}`}><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-white/70 shadow-sm dark:bg-black/15">{icon}</div><p className="mt-5 text-xs uppercase tracking-wider opacity-75">{label}</p><p className="mt-1 text-3xl font-semibold">{value}</p></div>}
function Legend({color,label,value,total}:{color:string;label:string;value:number;total:number}){return <div className="flex items-center justify-between rounded-xl bg-panel-hover px-3 py-2.5"><span className="flex items-center gap-2 text-sm"><i className={`h-2.5 w-2.5 rounded-full ${color}`}/>{label}</span><span className="font-medium">{value} <span className="text-xs text-ink-muted">({Math.round(value/total*100)}%)</span></span></div>}
function Mini({label,value,tone}:{label:string;value:number;tone:"lavender"|"mint"|"green"|"red"}){const styles={lavender:"bg-lavender-soft text-lavender",mint:"bg-mint-soft text-present",green:"bg-green-soft text-present",red:"bg-rose-soft text-absent"};return <div className={`rounded-xl p-4 ${styles[tone]}`}><p className="text-2xl font-semibold">{value}</p><p className="mt-1 text-[11px] opacity-75">{label}</p></div>}
