import { useEffect, useState } from "react";
import { Activity, CalendarClock, CheckCircle2, Users, XCircle } from "lucide-react";
import { Link } from "react-router-dom";
import { api } from "../api/client";
import { useAuth } from "../context/AuthContext";
import AdminSidebar from "../components/AdminSidebar";

type Student={student_id:string;name:string}; type Attendance={student_id?:string;name?:string;status?:string;time?:string}; type Session={session_id:string;name:string;start_time:string;duration_minutes:number;status:string};
export default function AdminDashboardPage(){
 const {name}=useAuth(); const [students,setStudents]=useState<Student[]>([]),[records,setRecords]=useState<Attendance[]>([]),[scheduled,setScheduled]=useState<Session[]>([]),[session,setSession]=useState<Session|null>(null),[pipelineRunning,setPipelineRunning]=useState(false);
 async function load(){try{const [studentsRes,currentRes,scheduledRes,statusRes]=await Promise.all([api.get("/students"),api.get("/session/current"),api.get("/session/scheduled"),api.get("/pipeline/status")]);const current=currentRes.data?.active?currentRes.data:null;setStudents(studentsRes.data?.students??[]);setSession(current);setScheduled(scheduledRes.data?.sessions??[]);setPipelineRunning(Boolean(statusRes.data?.running));if(current?.session_id){const r=await api.get(`/attendance/session/${current.session_id}`);setRecords(r.data?.records??[])}else setRecords([])}catch(e){console.error("Dashboard refresh failed",e)}}
 useEffect(()=>{void load();const t=window.setInterval(()=>void load(),5000);return()=>window.clearInterval(t)},[]);
 const present=records.filter(r=>r.status?.toLowerCase()==="present").length,late=records.filter(r=>r.status?.toLowerCase()==="late").length,absent=records.filter(r=>r.status?.toLowerCase()==="absent").length,rate=students.length?Math.round(((present+late)/students.length)*100):0,max=Math.max(students.length,1);
 return <div className="min-h-screen bg-bg text-ink"><AdminSidebar/><main className="w-full px-5 py-8 sm:px-8 lg:px-10 transition-[margin-left,width] duration-300" style={{marginLeft:"var(--portal-sidebar-offset,0px)",width:"calc(100% - var(--portal-sidebar-offset,0px))"}}>
 <section className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-accent">Welcome back{name?`, ${name}`:""}</p><h2 className="mt-1 font-display text-3xl font-semibold sm:text-4xl">Attendance Overview</h2><p className="mt-2 text-sm text-ink-muted">Track live sessions, scheduled lectures and attendance performance.</p></div><div className="flex items-center gap-2 rounded-xl border border-line bg-panel px-4 py-2.5 text-xs text-ink-muted shadow-sm"><span className={`h-2.5 w-2.5 rounded-full ${pipelineRunning?"animate-pulse bg-green-500":"bg-ink-faint"}`}/>{pipelineRunning?"AI Pipeline Active":"AI Pipeline Idle"}</div></section>
 <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={<Users size={20}/>} label="Total Students" value={students.length}/><Stat icon={<CheckCircle2 size={20}/>} label="Present" value={present}/><Stat icon={<XCircle size={20}/>} label="Absent" value={absent}/><Stat icon={<Activity size={20}/>} label="Current Rate" value={`${rate}%`}/></section>
 <section className="mt-6 grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><div className="rounded-2xl border border-line bg-panel p-6 shadow-sm"><div className="flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-accent">Live Analytics</p><h3 className="mt-1 text-lg font-semibold">Current Session Breakdown</h3></div><span className={`rounded-full px-3 py-1 text-xs ${session?"bg-green-50 text-green-700":"bg-panel-hover text-ink-muted"}`}>{session?"LIVE":"IDLE"}</span></div><div className="mt-7 space-y-5"><Bar label="Present" value={present} total={max}/><Bar label="Late" value={late} total={max}/><Bar label="Absent" value={absent} total={max}/></div><div className="mt-7 grid grid-cols-3 gap-3 text-center"><Mini label="Present" value={present}/><Mini label="Late" value={late}/><Mini label="Absent" value={absent}/></div></div><div className="rounded-2xl border border-line bg-panel p-6 shadow-sm"><div className="flex items-center gap-3"><div className="rounded-xl bg-accent-soft p-3 text-accent"><CalendarClock size={20}/></div><div><p className="text-xs uppercase tracking-wider text-ink-faint">Next session</p><h3 className="mt-1 font-semibold">{scheduled[0]?.name??"Nothing scheduled"}</h3></div></div>{scheduled[0]?<><p className="mt-5 text-sm text-ink-muted">{new Date(scheduled[0].start_time).toLocaleString()}</p><p className="mt-1 text-xs text-ink-faint">45-minute AI monitoring session</p></>:<p className="mt-5 text-sm text-ink-muted">Schedule a lecture to see it here.</p>}<Link to="/admin/schedule" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-accent px-4 py-2.5 text-sm font-medium text-white"><CalendarClock size={16}/>Manage Schedule</Link></div></section>
 <section className="mt-6 rounded-2xl border border-line bg-panel shadow-sm"><div className="flex items-center justify-between border-b border-line px-6 py-5"><div><h3 className="font-semibold">Current Session</h3><p className="mt-1 text-xs text-ink-muted">Session-specific attendance only.</p></div><span className="text-xs text-ink-muted">{records.length} records</span></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-line bg-panel-hover text-xs uppercase tracking-wider text-ink-faint"><tr><th className="px-6 py-3">Student</th><th className="px-6 py-3">ID</th><th className="px-6 py-3">Status</th><th className="px-6 py-3">Time</th></tr></thead><tbody>{records.map((r,i)=><tr key={`${r.student_id}-${i}`} className="border-b border-line last:border-0"><td className="px-6 py-4 font-medium">{r.name}</td><td className="px-6 py-4 text-ink-muted">{r.student_id}</td><td className="px-6 py-4"><span className="rounded-full bg-accent-soft px-3 py-1 text-xs text-accent">{r.status}</span></td><td className="px-6 py-4 text-ink-muted">{r.time??"—"}</td></tr>)}{!records.length&&<tr><td colSpan={4} className="px-6 py-12 text-center text-ink-muted">{session?"Waiting for AI attendance...":"No active session. Previous attendance is available in Attendance History."}</td></tr>}</tbody></table></div></section>
 </main></div>;
}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:string|number}){return <div className="rounded-2xl border border-line bg-panel p-5 shadow-sm"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-accent-soft text-accent">{icon}</div><p className="mt-5 text-xs uppercase tracking-wider text-ink-faint">{label}</p><p className="mt-1 text-3xl font-semibold">{value}</p></div>}
function Bar({label,value,total}:{label:string;value:number;total:number}){const width=Math.min(100,(value/total)*100);return <div><div className="mb-2 flex justify-between text-sm"><span>{label}</span><span className="font-medium">{value}</span></div><div className="h-3 overflow-hidden rounded-full bg-line"><div className="h-full rounded-full bg-accent transition-all" style={{width:`${width}%`}}/></div></div>}
function Mini({label,value}:{label:string;value:number}){return <div className="rounded-xl bg-panel-hover p-3"><p className="text-xl font-semibold">{value}</p><p className="mt-1 text-[11px] text-ink-muted">{label}</p></div>}
