import { useEffect, useMemo, useState } from "react";
import { CalendarDays, ChevronLeft, ChevronRight, CircleCheck, CircleX, Clock3, Play, Timer } from "lucide-react";
import AdminSidebar from "../components/AdminSidebar";
import { api } from "../api/client";

type RecordItem={student_id?:string;name?:string;status?:string;date?:string;time?:string;session_id?:string};
type Session={session_id:string;name:string;start_time:string;planned_start_time?:string;duration_minutes:number;status?:string;overdue?:boolean;ended_at?:string};
const keyFor=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const sessionDateKey=(value?:string)=>{if(!value)return "";const direct=value.match(/^(\d{4}-\d{2}-\d{2})/);if(direct)return direct[1];const d=new Date(value);return Number.isNaN(d.getTime())?"":keyFor(d)};
const PAGE_SIZE=6, SESSION_PAGE_SIZE=3;
function tone(status?:string){const s=status?.toLowerCase();return s==="present"?"bg-mint-soft text-present":s==="late"?"bg-sky-soft text-sky":"bg-rose-soft text-absent"}
function uniqueLatest(records:RecordItem[]){const map=new Map<string,RecordItem>();[...records].sort((a,b)=>`${b.date||""} ${b.time||""}`.localeCompare(`${a.date||""} ${a.time||""}`)).forEach(r=>{const id=r.student_id||r.name||"unknown";if(!map.has(id))map.set(id,r)});return [...map.values()]}
export default function AdminCalendarPage(){
 const [month,setMonth]=useState(()=>new Date()),[records,setRecords]=useState<RecordItem[]>([]),[scheduled,setScheduled]=useState<Session[]>([]),[history,setHistory]=useState<Session[]>([]),[selected,setSelected]=useState<string|null>(null),[page,setPage]=useState(1),[sessionPage,setSessionPage]=useState(1),[openSession,setOpenSession]=useState<string|null>(null);
 const days=useMemo(()=>new Date(month.getFullYear(),month.getMonth()+1,0).getDate(),[month]);
 const first=useMemo(()=>new Date(month.getFullYear(),month.getMonth(),1).getDay(),[month]);
 useEffect(()=>{let dead=false;async function load(){try{const [a,b]=await Promise.all([api.get("/session/scheduled"),api.get("/session/history")]);if(!dead){setScheduled(a.data?.sessions??[]);setHistory(b.data?.sessions??[])}}catch(e){console.error("Could not load session history",e)}const rs=(await Promise.all(Array.from({length:days},(_,i)=>api.get(`/attendance/${keyFor(new Date(month.getFullYear(),month.getMonth(),i+1))}`).then(r=>r.data?.records??[]).catch(()=>[])))).flat();if(!dead)setRecords(rs)}void load();return()=>{dead=true}},[month,days]);
 const byDate=useMemo(()=>{const m:Record<string,RecordItem[]>={};records.forEach(r=>{if(r.date)(m[r.date]??=[]).push(r)});return m},[records]);
 const sessionsByDate=useMemo(()=>{const m:Record<string,Session[]>={};const seen=new Set<string>();[...history,...scheduled].forEach(s=>{if(!s.session_id||seen.has(s.session_id))return;const k=sessionDateKey(s.planned_start_time||s.start_time);if(!k)return;seen.add(s.session_id);(m[k]??=[]).push(s)});Object.values(m).forEach(list=>list.sort((a,b)=>new Date(b.planned_start_time||b.start_time).getTime()-new Date(a.planned_start_time||a.start_time).getTime()));return m},[history,scheduled]);
 const prefix=`${month.getFullYear()}-${String(month.getMonth()+1).padStart(2,"0")}`;const monthRecords=records.filter(r=>r.date?.startsWith(prefix));const snapshot=uniqueLatest(monthRecords);
 const present=snapshot.filter(r=>r.status?.toLowerCase()==="present").length,late=snapshot.filter(r=>r.status?.toLowerCase()==="late").length,absent=snapshot.filter(r=>r.status?.toLowerCase()==="absent").length;
 const sessions=new Set([...history,...scheduled].filter(s=>sessionDateKey(s.planned_start_time||s.start_time).startsWith(prefix)).map(s=>s.session_id)).size;
 const selectedRecords=selected?byDate[selected]??[]:[],selectedSessions=selected?sessionsByDate[selected]??[]:[],visible=selectedRecords.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE),pages=Math.max(1,Math.ceil(selectedRecords.length/PAGE_SIZE)),sessionPages=Math.max(1,Math.ceil(selectedSessions.length/SESSION_PAGE_SIZE)),visibleSessions=selectedSessions.slice((sessionPage-1)*SESSION_PAGE_SIZE,sessionPage*SESSION_PAGE_SIZE),monthName=month.toLocaleDateString(undefined,{month:"long",year:"numeric"}),cells=Array.from({length:first+days},(_,i)=>i<first?null:i-first+1),today=keyFor(new Date());
 const sessionRecords=(id:string)=>uniqueLatest(selectedRecords.filter(r=>r.session_id===id));
 return <div className="min-h-screen bg-bg text-ink"><AdminSidebar/><main className="w-full px-5 py-8 sm:px-8 lg:px-10 transition-[margin-left,width] duration-300" style={{marginLeft:"var(--portal-sidebar-offset,0px)",width:"calc(100% - var(--portal-sidebar-offset,0px))"}}><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-accent">Admin Portal</p><h1 className="mt-1 font-display text-3xl font-semibold">Attendance Calendar</h1><p className="mt-2 text-sm text-ink-muted">Past attendance, scheduled sessions and daily status at a glance.</p>
 <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={<CircleCheck size={19}/>} label="Present" value={present} cls="bg-mint-soft text-present border-present/20"/><Stat icon={<Clock3 size={19}/>} label="Late" value={late} cls="bg-sky-soft text-sky border-sky/20"/><Stat icon={<CircleX size={19}/>} label="Absent" value={absent} cls="bg-rose-soft text-absent border-absent/20"/><Stat icon={<Timer size={19}/>} label="Sessions" value={sessions} cls="bg-lavender-soft text-lavender border-lavender/20"/></div>
 <section className="mt-6 rounded-2xl border border-line bg-panel p-5 shadow-sm"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="rounded-xl bg-blue-soft p-3 text-blue"><CalendarDays size={20}/></div><div><h2 className="font-semibold">{monthName}</h2><p className="text-xs text-ink-muted">Click a day to inspect its sessions.</p></div></div><div className="flex gap-2"><button onClick={()=>{setMonth(new Date(month.getFullYear(),month.getMonth()-1,1));setSelected(null);setOpenSession(null);setSessionPage(1)}} className="rounded-xl border border-line p-2 hover:bg-panel-hover"><ChevronLeft size={18}/></button><button onClick={()=>{setMonth(new Date());setSelected(null);setOpenSession(null);setSessionPage(1)}} className="rounded-xl border border-line px-3 py-2 text-xs font-medium hover:bg-panel-hover">Today</button><button onClick={()=>{setMonth(new Date(month.getFullYear(),month.getMonth()+1,1));setSelected(null);setOpenSession(null);setSessionPage(1)}} className="rounded-xl border border-line p-2 hover:bg-panel-hover"><ChevronRight size={18}/></button></div></div>
 <div className="mt-6 grid grid-cols-7 gap-2 text-center text-[10px] font-semibold uppercase tracking-wider text-ink-faint">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(x=><div key={x} className="py-2">{x}</div>)}{cells.map((day,i)=>{if(!day)return <div key={i} className="min-h-28"/>;const d=new Date(month.getFullYear(),month.getMonth(),day),date=keyFor(d),rs=byDate[date]??[],ss=sessionsByDate[date]??[],p=uniqueLatest(rs).filter(r=>r.status?.toLowerCase()==="present").length,l=uniqueLatest(rs).filter(r=>r.status?.toLowerCase()==="late").length,a=uniqueLatest(rs).filter(r=>r.status?.toLowerCase()==="absent").length;return <button key={date} onClick={()=>{setSelected(date);setPage(1);setSessionPage(1);setOpenSession(null)}} className={`min-h-28 rounded-xl border p-2 text-left transition hover:-translate-y-0.5 ${selected===date?"border-accent bg-accent-soft shadow-sm":"border-line bg-bg hover:bg-panel-hover"}`}><div className="flex items-center justify-between"><span className={`flex h-7 w-7 items-center justify-center rounded-full text-sm font-semibold ${today===date?"bg-accent text-white":""}`}>{day}</span>{ss.length>0&&<span className="rounded-full bg-lavender-soft px-2 py-0.5 text-[9px] font-semibold text-lavender">{ss.length} session{ss.length>1?"s":""}</span>}</div><div className="mt-3 space-y-1.5">{ss.slice(0,2).map(s=><div key={s.session_id} className={`truncate rounded-md px-2 py-1 text-[10px] font-semibold ${s.status==="scheduled"?"bg-lavender-soft text-lavender":"bg-peach-soft text-accent"}`}>{s.name||"Untitled Session"}</div>)}{ss.length>2&&<p className="text-[9px] text-ink-faint">+{ss.length-2} more</p>}{rs.length>0&&<div className="grid grid-cols-3 gap-1 text-[9px] font-semibold"><span className="rounded-md bg-mint-soft py-1 text-center text-present">{p}</span><span className="rounded-md bg-sky-soft py-1 text-center text-sky">{l}</span><span className="rounded-md bg-rose-soft py-1 text-center text-absent">{a}</span></div>}</div></button>})}</div></section>
 {selected&&<section className="mt-5 rounded-2xl border border-line bg-panel shadow-sm"><div className="border-b border-line px-6 py-5"><h2 className="font-semibold">{new Date(`${selected}T00:00:00`).toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric",year:"numeric"})}</h2><p className="mt-1 text-xs text-ink-muted">{selectedSessions.length} sessions</p></div><div className="p-5"><div className="mb-3 flex items-end justify-between gap-3"><div><h3 className="text-sm font-semibold">Sessions</h3><p className="mt-1 text-[11px] text-ink-muted">Click a session to view its attendance details.</p></div>{sessionPages>1&&<span className="text-[11px] text-ink-faint">Page {sessionPage} of {sessionPages}</span>}</div><div className="space-y-3">{visibleSessions.map(s=>{const open=openSession===s.session_id;const rs=sessionRecords(s.session_id);return <div key={s.session_id} className="overflow-hidden rounded-xl border border-lavender/20 bg-lavender-soft"><button onClick={()=>setOpenSession(open?null:s.session_id)} className="flex w-full items-center justify-between gap-4 p-4 text-left hover:bg-white/20"><div className="flex min-w-0 gap-3"><div className="rounded-lg bg-white/60 p-2 text-lavender dark:bg-black/15"><Play size={14}/></div><div className="min-w-0"><p className="truncate font-medium">{s.name||"Untitled Session"}</p><p className="mt-1 flex items-center gap-1 text-xs text-ink-muted"><Clock3 size={12}/>{new Date(s.planned_start_time||s.start_time).toLocaleTimeString(undefined,{hour:"numeric",minute:"2-digit"})} · {s.duration_minutes} min</p><p className="mt-1 text-[10px] text-ink-faint">{s.status==="scheduled"?"Scheduled":"Completed"} · ID {s.session_id.slice(-8)}</p></div></div><ChevronRight size={17} className={`shrink-0 transition-transform ${open?"rotate-90":""}`}/></button>{open&&<div className="border-t border-lavender/20 bg-panel p-4"><div className="mb-3 flex items-center justify-between"><h4 className="text-sm font-semibold">Attendance Details</h4><span className="text-[11px] text-ink-muted">{rs.length} students</span></div>{rs.length?<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{rs.map((r,i)=><div key={`${r.student_id}-${i}`} className={`rounded-xl border p-3 ${r.status?.toLowerCase()==="present"?"border-present/20 bg-mint-soft":r.status?.toLowerCase()==="late"?"border-sky/20 bg-sky-soft":"border-absent/20 bg-rose-soft"}`}><p className="font-medium">{r.name}</p><p className="mt-1 text-xs text-ink-muted">{r.student_id}</p><div className="mt-2 flex items-center justify-between"><span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${tone(r.status)}`}>{r.status}</span><span className="text-[11px] text-ink-muted">{r.time||"—"}</span></div></div>)}</div>:<p className="text-sm text-ink-muted">No attendance records for this session.</p>}</div>}</div>})}</div>{sessionPages>1&&<Pager page={sessionPage} total={sessionPages} onChange={setSessionPage}/>}</div></section>}
 </main></div>;
}
function Stat({icon,label,value,cls}:{icon:React.ReactNode;label:string;value:number;cls:string}){return <div className={`rounded-2xl border p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md ${cls}`}><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-white/65 shadow-sm dark:bg-black/15">{icon}</div><p className="mt-4 text-xs uppercase tracking-wider opacity-75">{label}</p><p className="mt-1 text-3xl font-semibold">{value}</p></div>}
function Pager({page,total,onChange}:{page:number;total:number;onChange:(p:number)=>void}){return <div className="mt-4 flex items-center justify-center gap-3 border-t border-line pt-4"><button disabled={page===1} onClick={()=>onChange(page-1)} className="rounded-lg border border-line p-2 disabled:opacity-30 hover:bg-panel-hover"><ChevronLeft size={16}/></button><span className="text-xs text-ink-muted">Page {page} of {total}</span><button disabled={page===total} onClick={()=>onChange(page+1)} className="rounded-lg border border-line p-2 disabled:opacity-30 hover:bg-panel-hover"><ChevronRight size={16}/></button></div>}
