import { FormEvent, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowLeft, Mail, ShieldCheck } from "lucide-react";
import { api } from "../api/client";

export default function ForgotPasswordPage(){
 const [email,setEmail]=useState(""); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setError("");setMessage("");setLoading(true);try{const r=await api.post("/auth/password/forgot",{email:email.trim().toLowerCase()});setMessage(r.data?.message||"If an eligible account exists, password-reset instructions have been sent to its verified email.");}catch(err:any){setError(err?.response?.data?.detail||"We couldn't process the request right now. Please try again.");}finally{setLoading(false)}}
 return <div className="min-h-screen bg-bg text-ink flex items-center justify-center px-6 py-12"><div className="w-full max-w-md"><Link to="/login" className="inline-flex items-center gap-2 text-sm text-ink-muted hover:text-ink"><ArrowLeft size={16}/> Back to login</Link><div className="mt-8 rounded-3xl border border-line bg-panel p-7 shadow-sm"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-accent-soft text-accent"><ShieldCheck size={20}/></div><h1 className="mt-5 font-display text-2xl font-semibold">Forgot your password?</h1><p className="mt-2 text-sm leading-6 text-ink-muted">Enter your account email. If it belongs to an active account with a verified email, we'll send a secure password-reset link there.</p><form onSubmit={submit} className="mt-6 space-y-4"><label className="block"><span className="mb-2 block text-sm font-medium">Email address</span><div className="relative"><Mail className="absolute left-3 top-1/2 -translate-y-1/2 text-ink-faint" size={17}/><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="w-full rounded-xl border border-line bg-bg py-3 pl-10 pr-3 text-sm outline-none focus:border-accent" placeholder="you@example.com"/></div></label>{error&&<p className="rounded-xl border border-red-300/40 bg-red-500/10 p-3 text-sm text-red-600">{error}</p>}{message&&<p className="rounded-xl border border-green-300/40 bg-green-500/10 p-3 text-sm text-green-700">{message}</p>}<button disabled={loading} className="w-full rounded-xl bg-accent px-4 py-3 text-sm font-medium text-white disabled:opacity-50">{loading?"Sending…":"Send reset link"}</button></form></div></div></div>;
}
