import { useEffect, useRef, useState } from "react";
import { Camera, CheckCircle2, Eye, EyeOff, KeyRound, Mail, Pencil, ShieldCheck, UserRound, Trash2, AlertTriangle } from "lucide-react";
import { api } from "../api/client";
import AdminSidebar from "../components/AdminSidebar";
import StudentSidebar from "../components/StudentSidebar";
import { useAuth } from "../context/AuthContext";
import { useNavigate } from "react-router-dom";

const GENDERS = ["male", "female", "prefer not to say"];

export default function ProfilePage() {
  const { role, name, studentId } = useAuth(); const navigate = useNavigate();
  const [profile, setProfile] = useState<any>(null); const [profileName, setProfileName] = useState(name ?? ""); const [email, setEmail] = useState(""); const [gender, setGender] = useState("");
  const [editing, setEditing] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [uploading, setUploading] = useState(false); const [removing, setRemoving] = useState(false); const [confirmRemove, setConfirmRemove] = useState(false); const fileRef = useRef<HTMLInputElement>(null);
  const [current, setCurrent] = useState(""); const [next, setNext] = useState(""); const [confirm, setConfirm] = useState(""); const [showCurrent, setShowCurrent] = useState(false); const [showNext, setShowNext] = useState(false); const [showConfirm, setShowConfirm] = useState(false); const [changingPassword, setChangingPassword] = useState(false);
  async function load() { try { const r = await api.get("/account/profile"); setProfile(r.data); setProfileName(r.data.name ?? ""); setEmail(r.data.email ?? ""); setGender(r.data.gender ?? ""); } catch (e:any) { setError(e?.response?.data?.detail ?? "Could not load profile."); } }
  useEffect(() => { void load(); }, []);
  async function saveProfile() { setError(""); setMessage(""); try { await api.put("/account/profile", { name: profileName, email: email.trim().toLowerCase() || null, gender: gender || null }); setEditing(false); setMessage("Profile updated successfully."); await load(); } catch (e:any) { setError(e?.response?.data?.detail ?? "Could not update profile."); } }
  async function changePassword() {
    setError(""); setMessage("");
    if (!current || !next || !confirm) { setError("Please fill in all password fields."); return; }
    if (next.length < 6) { setError("New password must be at least 6 characters."); return; }
    if (next !== confirm) { setError("New passwords do not match."); return; }
    if (current === next) { setError("Your new password must be different from your current password."); return; }
    setChangingPassword(true);
    try {
      await api.put("/account/password", { current_password: current, new_password: next, confirm_password: confirm });
      setCurrent(""); setNext(""); setConfirm("");
      localStorage.removeItem("va_token"); localStorage.removeItem("va_role"); localStorage.removeItem("va_name"); localStorage.removeItem("va_student_id");
      setMessage("Password changed successfully. You have been signed out for security.");
      window.setTimeout(() => navigate("/login", { replace: true }), 900);
    } catch(e:any) { setError(e?.response?.data?.detail ?? "Could not change password."); } finally { setChangingPassword(false); }
  }
  async function uploadPhoto(file: File) {
    setError(""); setMessage(""); if (!new Set(["image/jpeg","image/png","image/webp"]).has(file.type)) { setError("Only JPG, PNG or WebP images are allowed."); return; } if (file.size > 2 * 1024 * 1024) { setError("Profile photo must be 2 MB or smaller."); return; }
    const reader = new FileReader(); reader.onload = async () => { setUploading(true); try { await api.put("/account/photo", { image: reader.result }); setMessage("Profile photo updated."); await load(); } catch (e:any) { setError(e?.response?.data?.detail ?? "Could not upload photo."); } finally { setUploading(false); } }; reader.readAsDataURL(file);
  }
  async function removePhoto() { if (!profile?.profile_photo) return; setError(""); setMessage(""); setRemoving(true); try { await api.delete("/account/photo"); setConfirmRemove(false); setMessage("Profile photo removed. Default avatar restored."); await load(); } catch (e:any) { setError(e?.response?.data?.detail ?? "Could not remove photo."); } finally { setRemoving(false); } }
  const Sidebar = role === "student" ? StudentSidebar : AdminSidebar; const photo = profile?.profile_photo;
  return <div className="min-h-screen bg-bg text-ink"><Sidebar/><main className="w-full px-5 py-8 sm:px-8 lg:px-10" style={{marginLeft:"var(--portal-sidebar-offset,0px)",width:"calc(100% - var(--portal-sidebar-offset,0px))"}}>
    <p className="font-mono text-[10px] uppercase tracking-[0.18em] text-accent">Account</p><h1 className="mt-1 font-display text-3xl font-semibold">Profile & Security</h1><p className="mt-2 text-sm text-ink-muted">Manage your identity, profile photo, password and account security.</p>
    {(error||message)&&<div className={`mt-5 rounded-xl border px-4 py-3 text-sm ${error ? "border-absent/20 bg-absent/5 text-absent" : "border-line bg-panel text-ink-muted"}`}>{error||message}</div>}
    <section className="mt-6 rounded-2xl border border-line bg-panel p-6 shadow-sm"><div className="flex flex-wrap items-center gap-5 border-b border-line pb-6"><div className="relative"><div className="flex h-20 w-20 overflow-hidden items-center justify-center rounded-2xl bg-accent-soft text-accent">{photo?<img src={photo} alt="Profile" className="h-full w-full object-cover"/>:<UserRound size={32}/>}</div><button type="button" onClick={()=>fileRef.current?.click()} disabled={uploading||removing} title="Change profile photo" className="absolute -bottom-2 -right-2 rounded-full bg-accent p-2 text-white shadow disabled:opacity-50"><Camera size={14}/></button>{photo&&<button type="button" onClick={()=>setConfirmRemove(true)} disabled={uploading||removing} title="Remove profile photo" className="absolute -bottom-2 -left-2 rounded-full border border-line bg-panel p-2 text-absent shadow disabled:opacity-50"><Trash2 size={14}/></button>}<input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={e=>{const f=e.target.files?.[0];if(f)uploadPhoto(f);e.currentTarget.value=""}}/></div><div><h2 className="font-semibold text-lg">{profileName || "User"}</h2><p className="text-sm text-ink-muted">{role === "admin" ? "Administrator" : `Student${studentId ? ` · ${studentId}` : ""}`}</p><p className="mt-1 text-xs text-ink-faint">JPG, PNG or WebP · max 2 MB</p>{photo&&<p className="mt-1 text-xs text-ink-faint">Use the trash button to restore the default avatar.</p>}</div></div>
      <div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Name" value={profileName} disabled={!editing} onChange={setProfileName}/><Field label="Student ID / Username" value={profile?.student_id || profile?.username || studentId || "Administrator"} disabled/><Field label="Email" value={email} disabled={!editing} onChange={setEmail} type="email"/><div><label className="mb-1.5 block text-xs font-mono text-ink-muted">Gender</label><select value={gender} disabled={!editing} onChange={e=>setGender(e.target.value)} className="w-full rounded-xl border border-line bg-bg px-4 py-3 text-sm disabled:opacity-70"><option value="">Not set</option>{GENDERS.map(g=><option key={g} value={g}>{g === "prefer not to say" ? "Prefer not to say" : g[0].toUpperCase()+g.slice(1)}</option>)}</select></div></div>
      <div className="mt-5 flex gap-2">{editing?<><button type="button" onClick={saveProfile} className="inline-flex items-center gap-2 rounded-xl bg-accent px-4 py-2.5 text-sm font-medium text-white"><CheckCircle2 size={16}/> Save</button><button type="button" onClick={()=>{setEditing(false);void load()}} className="rounded-xl border border-line px-4 py-2.5 text-sm">Cancel</button></>:<button type="button" onClick={()=>setEditing(true)} className="inline-flex items-center gap-2 rounded-xl border border-line px-4 py-2.5 text-sm font-medium"><Pencil size={16}/> Edit profile</button>}</div>
    </section>
    <section className="mt-5 rounded-2xl border border-line bg-panel p-6 shadow-sm"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-accent-soft text-accent"><ShieldCheck size={19}/></div><div><h2 className="font-semibold">Account security</h2><p className="text-xs text-ink-muted">Review your current authentication status.</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Status label="Email" value={profile?.email_verified ? "Verified" : "Not verified"} good={!!profile?.email_verified}/><Status label="Sign-in" value={profile?.auth_provider === "google" ? "Google" : profile?.auth_provider === "both" ? "Google + password" : "Password"} good/><Status label="Account" value={profile?.is_active === false ? "Disabled" : "Active"} good={profile?.is_active !== false}/></div></section>
    <section className="mt-5 rounded-2xl border border-line bg-panel p-6 shadow-sm"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-accent-soft text-accent"><KeyRound size={19}/></div><div><h2 className="font-semibold">Change password</h2><p className="text-xs text-ink-muted">Your current password must be different from the new password.</p></div></div><div className="mt-5 space-y-3"><PasswordField value={current} setValue={setCurrent} show={showCurrent} toggle={()=>setShowCurrent(v=>!v)} placeholder="Current password" autoComplete="current-password"/><PasswordField value={next} setValue={setNext} show={showNext} toggle={()=>setShowNext(v=>!v)} placeholder="New password" autoComplete="new-password"/><PasswordField value={confirm} setValue={setConfirm} show={showConfirm} toggle={()=>setShowConfirm(v=>!v)} placeholder="Confirm new password" autoComplete="new-password"/><button type="button" disabled={changingPassword} onClick={()=>void changePassword()} className="inline-flex items-center gap-2 rounded-xl bg-accent px-5 py-2.5 text-sm font-medium text-white disabled:opacity-50"><KeyRound size={16}/>{changingPassword?"Changing…":"Change password"}</button></div></section>
    <section className="mt-5 rounded-2xl border border-line bg-panel p-6 shadow-sm"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-accent-soft text-accent"><Mail size={19}/></div><div><h2 className="font-semibold">Email security</h2><p className="text-xs text-ink-muted">Email verification and password recovery will use this address.</p></div></div><p className="mt-4 text-sm text-ink-muted">{profile?.email ? (profile?.email_verified ? "Your email is verified." : "Your email is not verified yet.") : "Add an email address to enable account recovery."}</p></section>
    {confirmRemove && <ConfirmDialog title="Remove profile photo?" text="Are you sure you want to remove your profile photo? Your default avatar will be restored." busy={removing} onCancel={()=>{if(!removing)setConfirmRemove(false)}} onConfirm={()=>void removePhoto()}/>} 
  </main></div>;
}
function Field({label,value,onChange,disabled,type="text"}:{label:string;value:string;onChange?:(v:string)=>void;disabled?:boolean;type?:string}) { return <div><label className="mb-1.5 block text-xs font-mono text-ink-muted">{label}</label><input type={type} value={value} disabled={disabled} onChange={e=>onChange?.(e.target.value)} className="w-full rounded-xl border border-line bg-bg px-4 py-3 text-sm disabled:opacity-70"/></div>; }
function Status({label,value,good}:{label:string;value:string;good:boolean}) { return <div className="rounded-xl border border-line bg-bg p-4"><p className="text-xs text-ink-faint">{label}</p><p className="mt-1 text-sm font-medium">{good?"✓ ":""}{value}</p></div>; }
function PasswordField({value,setValue,show,toggle,placeholder,autoComplete}:{value:string;setValue:(v:string)=>void;show:boolean;toggle:()=>void;placeholder:string;autoComplete:string}) { return <div className="relative"><input type={show?"text":"password"} value={value} onChange={e=>setValue(e.target.value)} placeholder={placeholder} autoComplete={autoComplete} className="w-full rounded-xl border border-line bg-bg px-4 py-3 pr-11 text-sm outline-none focus:border-accent"/><button type="button" onClick={toggle} className="absolute right-2 top-1/2 -translate-y-1/2 p-2 text-ink-faint hover:text-ink">{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div>; }
function ConfirmDialog({ title, text, busy, onCancel, onConfirm }: { title: string; text: string; busy: boolean; onCancel: () => void; onConfirm: () => void }) { return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/45 p-5 backdrop-blur-sm" onMouseDown={onCancel}><div className="w-full max-w-sm rounded-2xl border border-line bg-panel p-6 shadow-2xl" onMouseDown={e=>e.stopPropagation()}><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-red-500/10 text-red-500"><AlertTriangle size={22}/></div><h2 className="mt-4 text-center text-lg font-semibold">{title}</h2><p className="mt-2 text-center text-sm text-ink-muted">{text}</p><div className="mt-6 flex justify-end gap-2"><button disabled={busy} onClick={onCancel} className="rounded-lg px-4 py-2 text-sm text-ink-muted hover:bg-panel-hover disabled:opacity-50">Cancel</button><button disabled={busy} onClick={onConfirm} className="rounded-lg bg-red-500 px-4 py-2 text-sm font-medium text-white hover:bg-red-600 disabled:opacity-50">{busy ? "Removing…" : "Remove photo"}</button></div></div></div>; }
