import { FormEvent, useMemo, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { ArrowLeft, KeyRound, ShieldCheck } from "lucide-react";
import { api } from "../api/client";

export default function ResetPasswordPage(){
 const [params]=useSearchParams(); const token=useMemo(()=>params.get("token")||"",[params]); const [password,setPassword]=useState(""); const [confirm,setConfirm]=useState(""); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [loading,setLoading]=useState(false); const [done,setDone]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setError("");setMessage("");if(!token){setError("This password reset link is missing its token.");return}if(password.length<6){setError("Password must be at least 6 characters.");return}if(password!==confirm){setError("Passwords do not match.");return}setLoading(true);try{const r=await api.post("/auth/password/reset",{token,new_password:password,confirm_password:confirm});setMessage(r.data?.message||"Password reset successfully. You can now log in.");setDone(true)}catch(err:any){setError(err?.response?.data?.detail||"This reset link is invalid or expired. Please request a new one.")}finally{setLoading(false)}}
 return <div className="min-h-screen bg-bg text-ink flex items-center justify-center px-6 py-12"><div className="w-full max-w-md"><Link to="/login" className="inline-flex items-center gap-2 text-sm text-ink-muted hover:text-ink"><ArrowLeft size={16}/> Back to login</Link><div className="mt-8 rounded-3xl border border-line bg-panel p-7 shadow-sm"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-accent-soft text-accent"><KeyRound size={20}/></div><h1 className="mt-5 font-display text-2xl font-semibold">Create a new password</h1><p className="mt-2 text-sm leading-6 text-ink-muted">Choose a new password for your VisionAttend AI account.</p>{!done?<form onSubmit={submit} className="mt-6 space-y-4"><label className="block"><span className="mb-2 block text-sm font-medium">New password</span><input required minLength={6} maxLength={72} type="password" value={password} onChange={e=>setPassword(e.target.value)} className="w-full rounded-xl border border-line bg-bg px-3 py-3 text-sm outline-none focus:border-accent"/></label><label className="block"><span className="mb-2 block text-sm font-medium">Confirm new password</span><input required minLength={6} maxLength={72} type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} className="w-full rounded-xl border border-line bg-bg px-3 py-3 text-sm outline-none focus:border-accent"/></label>{error&&<p className="rounded-xl border border-red-300/40 bg-red-500/10 p-3 text-sm text-red-600">{error}</p>}<button disabled={loading||!token} className="w-full rounded-xl bg-accent px-4 py-3 text-sm font-medium text-white disabled:opacity-50">{loading?"Updating…":"Reset password"}</button></form>:<div className="mt-6 space-y-4"><p className="rounded-xl border border-green-300/40 bg-green-500/10 p-3 text-sm text-green-700">{message}</p><Link to="/login" className="inline-flex w-full items-center justify-center rounded-xl bg-accent px-4 py-3 text-sm font-medium text-white">Continue to login</Link></div>} {!done&&<p className="mt-5 flex items-center gap-2 text-xs text-ink-faint"><ShieldCheck size={14}/> Reset links expire and can only be used once.</p>}</div></div></div>;
}
