import { useEffect, useRef, useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import { ArrowRight, CheckCircle2, Hash, Lock, ScanFace, UserRound, Camera, RotateCcw } from "lucide-react";
import ViewfinderFrame from "../components/ViewfinderFrame";
import Logo from "../components/Logo";
import { useAuth } from "../context/AuthContext";

export default function SignupPage() {
  const [studentId, setStudentId] = useState("");
  const [name, setName] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [faceImage, setFaceImage] = useState("");
  const [cameraOpen, setCameraOpen] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [success, setSuccess] = useState(false);
  const videoRef = useRef<HTMLVideoElement | null>(null);
  const streamRef = useRef<MediaStream | null>(null);
  const { signup } = useAuth();
  const navigate = useNavigate();

  async function openCamera() {
    setError(null);
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: "user" }, audio: false });
      streamRef.current = stream;
      setCameraOpen(true);
      requestAnimationFrame(() => {
        if (videoRef.current) videoRef.current.srcObject = stream;
      });
    } catch {
      setError("Camera permission was denied or the camera is unavailable.");
    }
  }

  function closeCamera() {
    streamRef.current?.getTracks().forEach(track => track.stop());
    streamRef.current = null;
    setCameraOpen(false);
  }

  function captureFace() {
    const video = videoRef.current;
    if (!video || video.readyState < 2) {
      setError("Camera is not ready yet.");
      return;
    }

    const canvas = document.createElement("canvas");
    canvas.width = video.videoWidth;
    canvas.height = video.videoHeight;
    canvas.getContext("2d")?.drawImage(video, 0, 0, canvas.width, canvas.height);
    setFaceImage(canvas.toDataURL("image/jpeg", 0.88));
    closeCamera();
  }

  useEffect(() => () => closeCamera(), []);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError(null);

    if (!faceImage) {
      setError("Capture your face before creating the account.");
      return;
    }
    if (password !== confirmPassword) {
      setError("Passwords don't match.");
      return;
    }
    if (password.length < 6) {
      setError("Password must be at least 6 characters.");
      return;
    }

    setLoading(true);
    try {
      await signup(studentId.trim(), name.trim(), password, faceImage);
      setSuccess(true);
      setTimeout(() => navigate("/login"), 1500);
    } catch (err: any) {
      setError(err?.response?.data?.detail ?? "Registration failed. Please try again.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="min-h-screen bg-bg flex">
      <div className="hidden lg:flex lg:w-[45%] relative overflow-hidden bg-panel-dark items-center justify-center">
        <div className="absolute inset-0 opacity-40" style={{ backgroundImage: "radial-gradient(circle at 25% 75%, rgba(56,189,248,0.35), transparent 55%), radial-gradient(circle at 80% 20%, rgba(56,189,248,0.2), transparent 50%)" }} />
        <div className="relative z-10 flex flex-col items-center px-10 text-center">
          <div className="relative mb-8 animate-float">
            <ViewfinderFrame active cornerSize={22} className="relative w-40 h-40 rounded-2xl bg-white/5 border border-white/10 backdrop-blur-sm flex items-center justify-center">
              <div className="absolute inset-0 rounded-full border border-accent-glow/40 animate-pulse-ring" />
              <ScanFace className="text-accent-glow" size={56} strokeWidth={1.5} />
            </ViewfinderFrame>
          </div>
          <h2 className="font-display text-2xl font-semibold text-white mb-3">One face, one record</h2>
          <p className="text-white/60 text-sm leading-relaxed max-w-xs">Your face embedding is securely generated by the same VisionAttend recognition system used during attendance.</p>
        </div>
      </div>

      <div className="flex-1 flex items-center justify-center px-6 py-10">
        <div className="w-full max-w-sm">
          <Link to="/" className="inline-block mb-8"><Logo size={26} /></Link>
          <h1 className="font-display text-2xl font-semibold mb-1">Create your account</h1>
          <p className="text-sm text-ink-muted mb-7">Register your student details and capture one clear face.</p>

          {success ? (
            <div className="flex flex-col items-center py-10 text-center"><CheckCircle2 className="text-present mb-3" size={36}/><p className="text-sm text-ink-muted">Account and face registered. Taking you to login...</p></div>
          ) : (
            <form onSubmit={handleSubmit} className="space-y-4">
              <Field icon={<Hash size={16}/>} label="Student ID" value={studentId} onChange={setStudentId} placeholder="e.g. CW003" />
              <Field icon={<UserRound size={16}/>} label="Full name" value={name} onChange={setName} placeholder="e.g. Ali Khan" />

              <div>
                <label className="block text-xs font-mono text-ink-muted mb-1.5">Face registration</label>
                {faceImage ? (
                  <div className="rounded-xl border border-green-200 bg-green-50 p-3">
                    <div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2 text-sm text-green-700"><CheckCircle2 size={17}/> Face captured</div><button type="button" onClick={() => setFaceImage("")} className="text-xs text-green-700 hover:underline">Retake</button></div>
                  </div>
                ) : (
                  <button type="button" onClick={openCamera} className="w-full flex items-center justify-center gap-2 rounded-xl border border-line bg-white py-3 text-sm font-medium hover:border-accent hover:text-accent"><Camera size={17}/> Open camera & capture face</button>
                )}
              </div>

              {cameraOpen && (
                <div className="rounded-2xl border border-line bg-black p-2">
                  <video ref={videoRef} autoPlay playsInline muted className="aspect-video w-full rounded-xl object-cover" />
                  <div className="flex gap-2 pt-2"><button type="button" onClick={captureFace} className="flex-1 rounded-xl bg-accent py-2.5 text-sm font-medium text-white"><Camera size={16} className="mr-2 inline"/>Capture</button><button type="button" onClick={closeCamera} className="rounded-xl border border-line bg-white px-4 py-2.5 text-sm">Close</button></div>
                </div>
              )}

              <Field icon={<Lock size={16}/>} label="Password" value={password} onChange={setPassword} type="password" />
              <Field icon={<Lock size={16}/>} label="Confirm password" value={confirmPassword} onChange={setConfirmPassword} type="password" />

              {error && <p className="text-sm text-absent bg-absent/5 border border-absent/20 rounded-lg px-3 py-2">{error}</p>}

              <button type="submit" disabled={loading || cameraOpen} className="w-full flex items-center justify-center gap-2 bg-accent text-white font-medium py-2.5 rounded-lg shadow-sm hover:bg-accent-dim transition-all disabled:opacity-60">{loading ? "Registering face..." : "Create account"}{!loading && <ArrowRight size={16}/>}</button>
            </form>
          )}

          {!success && <p className="text-sm text-ink-muted mt-8 text-center">Already have an account? <Link to="/login" className="text-accent font-medium hover:underline">Log in</Link></p>}
        </div>
      </div>
    </div>
  );
}

function Field({ icon, label, value, onChange, placeholder, type = "text" }: { icon: React.ReactNode; label: string; value: string; onChange: (value: string) => void; placeholder?: string; type?: string }) {
  return <div><label className="block text-xs font-mono text-ink-muted mb-1.5">{label}</label><div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-ink-faint">{icon}</span><input type={type} value={value} onChange={e => onChange(e.target.value)} required placeholder={placeholder} className="w-full bg-white border border-line rounded-lg pl-9 pr-3 py-2.5 text-sm shadow-sm focus:outline-none focus:border-accent focus:ring-2 focus:ring-accent-soft transition-all"/></div></div>;
}
