import { useEffect, useMemo, useState } from "react";
import { CalendarDays, ChevronLeft, ChevronRight, Clock3 } from "lucide-react";
import { api } from "../api/client";
import StudentSidebar from "../components/StudentSidebar";

type RecordItem = { date: string; session_id?: string; session_name?: string; status: string; start_time?: string; duration_minutes?: number; time?: string; timestamp?: string };
const statusClass = (status:string) => status === "Present" ? "bg-mint-soft text-present border-emerald-200/40" : status === "Late" ? "bg-amber-100 text-amber-700 border-amber-300/30 dark:bg-amber-500/15 dark:text-amber-300" : "bg-rose-soft text-absent border-red-200/40";
const sessionTime = (r: RecordItem) => { const value = r.start_time || r.timestamp || r.time; if (!value) return "Time not recorded"; const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? String(value) : parsed.toLocaleTimeString(undefined,{hour:"numeric",minute:"2-digit"}); };

export default function StudentCalendarPage() {
  const [records,setRecords]=useState<RecordItem[]>([]); const [month,setMonth]=useState(new Date()); const [selected,setSelected]=useState<string | null>(null);
  useEffect(()=>{api.get("/me/attendance").then(r=>setRecords(r.data.records??[])).catch(()=>{});},[]);
  const keyMap=useMemo(()=>{const m:Record<string,RecordItem[]>={}; records.forEach(r=>(m[r.date]??=[]).push(r)); return m;},[records]);
  const year=month.getFullYear(), mon=month.getMonth(), first=new Date(year,mon,1).getDay(), days=new Date(year,mon+1,0).getDate();
  const cells=Array.from({length:first+days},(_,i)=>i<first?null:i-first+1); const selectedRecords=selected ? keyMap[selected] ?? [] : [];
  return <div className="min-h-screen bg-bg text-ink"><StudentSidebar/><main className="w-full px-5 py-8 sm:px-8 lg:px-10" style={{marginLeft:"var(--portal-sidebar-offset,0px)",width:"calc(100% - var(--portal-sidebar-offset,0px))"}}>
    <p className="font-mono text-[10px] uppercase tracking-[0.18em] text-accent">Student Portal</p><h1 className="mt-1 font-display text-3xl font-semibold">Attendance Calendar</h1><p className="mt-2 text-sm text-ink-muted">See Present, Late and Absent status for every recorded session.</p>
    <section className="mt-7 rounded-2xl border border-line bg-panel p-5 shadow-sm"><div className="flex items-center justify-between"><button onClick={()=>setMonth(new Date(year,mon-1,1))} className="rounded-xl border border-line p-2 hover:bg-panel-hover"><ChevronLeft size={18}/></button><div className="flex items-center gap-3"><CalendarDays size={19} className="text-accent"/><h2 className="text-lg font-semibold">{month.toLocaleString("default",{month:"long",year:"numeric"})}</h2></div><button onClick={()=>setMonth(new Date(year,mon+1,1))} className="rounded-xl border border-line p-2 hover:bg-panel-hover"><ChevronRight size={18}/></button></div>
      <div className="mt-6 grid grid-cols-7 gap-2 text-center text-[10px] font-mono uppercase text-ink-faint">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(d=><div key={d} className="py-2">{d}</div>)}{cells.map((day,i)=>{if(!day)return <div key={`blank-${i}`}/>; const date=`${year}-${String(mon+1).padStart(2,"0")}-${String(day).padStart(2,"0")}`; const dayRecords=keyMap[date]??[]; const statuses=[...new Set(dayRecords.map(r=>r.status))]; return <button key={date} onClick={()=>setSelected(date)} className={`min-h-20 rounded-xl border p-2 text-left transition hover:-translate-y-0.5 hover:shadow-sm ${selected===date?"border-accent ring-1 ring-accent":"border-line bg-bg"}`}><span className="text-xs font-semibold">{day}</span><div className="mt-2 space-y-1">{statuses.slice(0,3).map(s=><div key={s} className={`rounded-md px-1.5 py-1 text-[9px] font-semibold ${statusClass(s)}`}>{s}</div>)}</div></button>})}</div>
      <div className="mt-5 flex flex-wrap gap-3 border-t border-line pt-4 text-xs"><span className="rounded-full bg-mint-soft px-3 py-1 text-present">● Present</span><span className="rounded-full bg-amber-100 px-3 py-1 text-amber-700 dark:bg-amber-500/15 dark:text-amber-300">● Late</span><span className="rounded-full bg-rose-soft px-3 py-1 text-absent">● Absent</span></div>
    </section>
    {selected && <section className="mt-5 rounded-2xl border border-line bg-panel p-6 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-mono uppercase tracking-wider text-accent">Session details</p><h2 className="mt-1 text-lg font-semibold">{selected}</h2></div><button onClick={()=>setSelected(null)} className="text-xs text-ink-muted hover:text-ink">Close</button></div><div className="mt-5 space-y-3">{selectedRecords.length?selectedRecords.map((r,i)=><div key={i} className="flex flex-col gap-3 rounded-xl border border-line bg-bg px-4 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{r.session_name||"Attendance Session"}</p><div className="mt-1 flex flex-wrap items-center gap-3 text-xs text-ink-muted"><span className="inline-flex items-center gap-1.5"><Clock3 size={13}/>{sessionTime(r)}</span>{r.duration_minutes ? <span>{r.duration_minutes} min</span> : null}{r.session_id ? <span className="font-mono">#{r.session_id.slice(-6)}</span> : null}</div></div><span className={`self-start rounded-full px-2.5 py-1 text-[10px] font-semibold sm:self-auto ${statusClass(r.status)}`}>{r.status}</span></div>):<p className="text-sm text-ink-muted">No session records for this day.</p>}</div></section>}
  </main></div>;
}
