import { useEffect, useRef, useState } from "react";
import { Bell, CalendarClock, CheckCircle2, Radio, Trash2, X } from "lucide-react";
import { api } from "../api/client";

type Notice = { id: string; title: string; text: string; kind: "live" | "scheduled" | "attendance"; createdAt: number };
const STORAGE_KEY = "va_notifications";

export default function NotificationCenter() {
  const [open, setOpen] = useState(false);
  const [notices, setNotices] = useState<Notice[]>(() => { try { return JSON.parse(localStorage.getItem(STORAGE_KEY) || "[]"); } catch { return []; } });
  const rootRef = useRef<HTMLDivElement>(null);
  function save(items: Notice[]) { setNotices(items); localStorage.setItem(STORAGE_KEY, JSON.stringify(items)); }
  function add(notice: Omit<Notice, "createdAt">) { if (notices.some(n => n.id === notice.id)) return; save([{ ...notice, createdAt: Date.now() }, ...notices].slice(0, 50)); }
  async function refresh() { try { const [currentRes, scheduledRes] = await Promise.all([api.get("/session/current"), api.get("/session/scheduled")]); const current=currentRes.data; const scheduled=scheduledRes.data?.sessions??[]; if(current?.active)add({id:`live-${current.session_id}`,title:"AI session started",text:`${current.name??"Untitled Session"} is being monitored live.`,kind:"live"}); scheduled.forEach((s:any)=>add({id:`scheduled-${s.session_id}`,title:"Session scheduled",text:`${s.name??"Untitled Session"} is scheduled for ${new Date(s.planned_start_time||s.start_time).toLocaleString([], {dateStyle:"medium",timeStyle:"short"})}.`,kind:"scheduled"})); } catch {} }
  useEffect(() => { void refresh(); const timer=window.setInterval(()=>void refresh(),5000); return ()=>window.clearInterval(timer); }, [notices]);
  useEffect(() => { if(!open)return; const close=(e:MouseEvent)=>{if(rootRef.current&&!rootRef.current.contains(e.target as Node))setOpen(false)}; document.addEventListener("mousedown",close); return ()=>document.removeEventListener("mousedown",close); }, [open]);
  const icon=(kind:Notice["kind"])=>kind==="live"?<Radio size={16}/>:kind==="scheduled"?<CalendarClock size={16}/>:<CheckCircle2 size={16}/>;
  return <div ref={rootRef} className="relative"><button onClick={()=>setOpen(v=>!v)} className="relative rounded-xl border border-line bg-panel p-2.5 text-ink-muted hover:bg-panel-hover hover:text-ink" aria-label="Notifications"><Bell size={19}/>{notices.length>0&&<span className="absolute right-2 top-2 h-2 w-2 rounded-full bg-accent"/>}</button>{open&&<div className="absolute right-0 top-12 z-50 w-96 rounded-2xl border border-line bg-panel p-3 shadow-xl"><div className="flex items-center justify-between border-b border-line px-2 pb-3"><div><p className="font-semibold">Notifications</p><p className="text-xs text-ink-muted">Your notification history</p></div><div className="flex gap-1"><button onClick={()=>save([])} className="rounded-lg p-2 text-ink-muted hover:bg-panel-hover" title="Clear all"><Trash2 size={15}/></button><button onClick={()=>setOpen(false)} className="rounded-lg p-2 text-ink-muted hover:bg-panel-hover"><X size={15}/></button></div></div><div className="mt-2 max-h-[420px] space-y-2 overflow-y-auto">{notices.length?notices.map(n=><div key={n.id} className="flex gap-3 rounded-xl bg-panel-hover p-3"><div className="mt-0.5 text-accent">{icon(n.kind)}</div><div className="min-w-0"><p className="text-sm font-medium">{n.title}</p><p className="mt-1 text-xs leading-5 text-ink-muted">{n.text}</p><p className="mt-1 text-[10px] text-ink-faint">{new Date(n.createdAt).toLocaleString()}</p></div></div>):<div className="py-12 text-center text-sm text-ink-muted">No notifications</div>}</div>{notices.length>0&&<button onClick={()=>save([])} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border border-line py-2 text-xs font-medium text-ink-muted hover:bg-panel-hover"><Trash2 size={14}/> Clear all notifications</button>}</div>}</div>;
}
