import { createContext, useContext, useState, useEffect } from "react";
import type { ReactNode } from "react";
import { api } from "../api/client";

type Role = "admin" | "student";
type Theme = "light" | "dark";
interface AuthState { token: string | null; role: Role | null; name: string | null; studentId: string | null; }
interface GoogleResult { onboardingRequired: boolean; email?: string; suggestedName?: string; role?: Role; }
interface LoginResult { requires2FA: boolean; role?: Role; challenge?: string; maskedEmail?: string; }
interface SignupFaceData { faceImages: string[]; }
interface AuthContextValue extends AuthState { isAuthenticated:boolean; authReady:boolean; theme:Theme; toggleTheme:()=>void; login:(username:string,password:string,captchaToken:string)=>Promise<LoginResult>; verify2FA:(challenge:string,code:string)=>Promise<Role>; signup:(studentId:string,name:string,password:string,faceData:SignupFaceData,email:string,gender:string)=>Promise<void>; googleLogin:(credential:string)=>Promise<GoogleResult>; googleOnboard:(credential:string,data:{username:string;studentId:string;password:string;gender:string;faceData:SignupFaceData})=>Promise<Role>; logout:()=>void; }
const AuthContext=createContext<AuthContextValue|undefined>(undefined);
function persistAuth(response:any){const {access_token,role,name,student_id}=response.data??response;localStorage.setItem("va_token",access_token);localStorage.setItem("va_role",role);if(name)localStorage.setItem("va_name",name);else localStorage.removeItem("va_name");if(student_id)localStorage.setItem("va_student_id",student_id);else localStorage.removeItem("va_student_id");return {token:access_token,role:role as Role,name:name??null,studentId:student_id??null};}
function consentPayload(){try{const c=JSON.parse(localStorage.getItem("va_signup_consent")||"null");if(!c?.terms||!c?.privacy||!c?.biometric||!c?.attendance)throw new Error("Please review and accept the required legal and attendance consent before signing up.");return c;}catch(error){throw error instanceof Error?error:new Error("Please review and accept the required legal and attendance consent before signing up.");}}
async function recordConsent(identity:{username?:string;student_id?:string;email?:string}){consentPayload();const prefs=JSON.parse(localStorage.getItem("va_cookie_preferences")||"{}");const result=await api.post("/legal/consent",{...identity,terms_accepted:true,privacy_accepted:true,biometric_accepted:true,attendance_accepted:true,cookie_analytics:prefs?.analytics===true,cookie_marketing:prefs?.marketing===true});if(!result.data?.success)throw new Error(result.data?.message||"Legal consent could not be recorded.");}
export function AuthProvider({children}:{children:ReactNode}){
 const[state,setState]=useState<AuthState>({token:null,role:null,name:null,studentId:null});const[authReady,setAuthReady]=useState(false);const[theme,setTheme]=useState<Theme>(()=>(localStorage.getItem("va_theme") as Theme)||"light");
 useEffect(()=>{document.documentElement.classList.toggle("dark",theme==="dark");localStorage.setItem("va_theme",theme)},[theme]);
 useEffect(()=>{const token=localStorage.getItem("va_token"),role=localStorage.getItem("va_role") as Role|null,name=localStorage.getItem("va_name"),studentId=localStorage.getItem("va_student_id");if(token&&role)setState({token,role,name,studentId});setAuthReady(true)},[]);
 async function login(username:string,password:string,captchaToken:string):Promise<LoginResult>{const response=await api.post("/auth/login",{username,password,captcha_token:captchaToken});if(response.data?.requires_2fa)return{requires2FA:true,challenge:response.data.challenge,maskedEmail:response.data.masked_email};const next=persistAuth(response);setState(next);return{requires2FA:false,role:next.role};}
 async function verify2FA(challenge:string,code:string):Promise<Role>{const response=await api.post("/auth/2fa/verify",{code},{params:{challenge}});const next=persistAuth(response);setState(next);return next.role;}
 async function signup(studentId:string,name:string,password:string,faceData:SignupFaceData,email:string,gender:string){await recordConsent({username:studentId,student_id:studentId,email});await api.post("/auth/signup",{student_id:studentId,name,email,password,gender,face_images:faceData.faceImages});}
 async function googleLogin(credential:string):Promise<GoogleResult>{const response=await api.post("/auth/google",{credential});if(response.data?.onboarding_required)return{onboardingRequired:true,email:response.data.email,suggestedName:response.data.suggested_name};const next=persistAuth(response);setState(next);return{onboardingRequired:false,role:next.role};}
 async function googleOnboard(credential:string,data:{username:string;studentId:string;password:string;gender:string;faceData:SignupFaceData}):Promise<Role>{await recordConsent({username:data.username,student_id:data.studentId});const response=await api.post("/auth/google",{credential,username:data.username,student_id:data.studentId,password:data.password,gender:data.gender,face_images:data.faceData.faceImages});const next=persistAuth(response);setState(next);return next.role;}
 function logout(){localStorage.removeItem("va_token");localStorage.removeItem("va_role");localStorage.removeItem("va_name");localStorage.removeItem("va_student_id");setState({token:null,role:null,name:null,studentId:null});}
 return <AuthContext.Provider value={{...state,isAuthenticated:!!state.token,authReady,theme,toggleTheme:()=>setTheme(t=>t==="light"?"dark":"light"),login,verify2FA,signup,googleLogin,googleOnboard,logout}}>{children}</AuthContext.Provider>;
}
export function useAuth(){const ctx=useContext(AuthContext);if(!ctx)throw new Error("useAuth must be used within an AuthProvider");return ctx;}
